# -*- coding: utf-8 -*-
"""Maiz_mapa_datos_limpiar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EL9d_dgZhGcCd_ogswochyF07lK4YshV
"""

import pandas as pd
import geopandas as gpd

base_folder = '/content/drive/MyDrive/30DayMapChallenge2025/'

df_maiz_forrajero = pd.read_csv(base_folder+'Inegi_maiz_forrajero.csv',
                                sep=',', header=0).drop(columns=['Estrato'])

df_maiz_amarillo = pd.read_csv(base_folder+'Inegi_maiz_grano_amarillo.csv',
                                sep=',', header=0).drop(columns=['Estrato'])

df_maiz_blanco = pd.read_csv(base_folder+'Inegi_maiz_grano_blanco.csv',
                                sep=',', header=0).drop(columns=['Estrato'])

colsnames = [ 'clave', 'entidad', 'municipio', 'valor']
df_maiz_amarillo.columns = colsnames
df_maiz_forrajero.columns = colsnames
df_maiz_blanco.columns = colsnames


df_maiz_forrajero.rename(columns={'valor':'maiz_forrajero'}, inplace=True)
df_maiz_amarillo.rename(columns={'valor':'maiz_amarillo'}, inplace=True)
df_maiz_blanco.rename(columns={'valor':'maiz_blanco'}, inplace=True)

merged_df = pd.merge(df_maiz_forrajero, df_maiz_amarillo, on=['clave', 'entidad', 'municipio'], how='outer')
merged_df = pd.merge(merged_df, df_maiz_blanco, on=['clave', 'entidad', 'municipio'], how='outer')

merged_df['clave'] = merged_df['clave'].astype('int')

merged_df.to_csv(base_folder+'Inegi_maiz_data.csv', index=False)
merged_df.head()

map_municipios = gpd.read_file('/content/drive/MyDrive/30DayMapChallenge2025/mun23gw_c/mun23cw.shp')

map_municipios.columns = [nombre.lower() for nombre in map_municipios.columns]

map_municipios['cvegeo'] = map_municipios['cvegeo'].astype('int')

map_municipios.head()

merged_df_all = pd.merge(map_municipios, merged_df, left_on=['cvegeo', 'nom_ent'], right_on=['clave', 'entidad'],
         how='left')
merged_gdf = gpd.GeoDataFrame(merged_df_all, geometry='geometry', crs='EPSG:4326')

print("Number of rows before dropping:", len(merged_gdf))

# Check for null or empty geometries
null_geometries = merged_gdf.geometry.isnull().any()
empty_geometries = merged_gdf.geometry.is_empty.any()

print(f"Are there any null geometries? {null_geometries}")
print(f"Are there any empty geometries? {empty_geometries}")

# Drop rows with null geometries if any exist
if null_geometries:
    merged_gdf = merged_gdf.dropna(subset=['geometry'])

print("Number of rows after dropping:", len(merged_gdf))

output_geojson_path = base_folder + 'mexico_maiz_data.geojson'
merged_gdf.to_file(output_geojson_path, driver='GeoJSON')
print(f"GeoJSON file saved to: {output_geojson_path}")



if merged_gdf.crs is None:
    print("GeoDataFrame has no CRS defined. Assuming EPSG:4326 for now, but you might need to set the correct one.")
    merged_gdf = merged_gdf.set_crs('EPSG:4326', allow_override=True)
elif merged_gdf.crs != 'EPSG:4326':
    print(f"Reprojecting GeoDataFrame from {merged_gdf.crs} to EPSG:4326")
    merged_gdf = merged_gdf.to_crs(epsg=4326)

# Save the GeoDataFrame to GeoJSON
output_geojson_path = base_folder + 'mexico_maiz_data.geojson'
merged_gdf.to_file(output_geojson_path, driver='GeoJSON')

print(f"GeoJSON file saved to: {output_geojson_path}")